apiVersion: kueue.x-k8s.io/v1beta1
kind: ResourceFlavor
metadata:
  name: v100-flavor
spec:
  tolerations:
    - key: "nvidia.com/gpu.product"
      operator: "Equal"
      value: "Tesla-V100-PCIE-32GB"
      effect: "NoSchedule"
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: ResourceFlavor
metadata:
  name: a100-flavor
spec:
  tolerations:
    - key: "nvidia.com/gpu.product"
      operator: "Equal"
      value: "NVIDIA-A100-SXM4-40GB"
      effect: "NoSchedule"
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: ResourceFlavor
metadata:
  name: h100-flavor
spec:
  tolerations:
    - key: "nvidia.com/gpu.product"
      operator: "Equal"
      value: "NVIDIA-H100-80GB-HBM3"
      effect: "NoSchedule"
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: v100-clusterqueue
spec:
  namespaceSelector: {}
  resourceGroups:
    - coveredResources: ["nvidia.com/gpu"]
      flavors:
        - name: "v100-flavor"
          resources:
            - name: "nvidia.com/gpu"
              nominalQuota: 3
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: a100-clusterqueue
spec:
  namespaceSelector: {}
  resourceGroups:
    - coveredResources: ["nvidia.com/gpu"]
      flavors:
        - name: "a100-flavor"
          resources:
            - name: "nvidia.com/gpu"
              nominalQuota: 0
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: h100-clusterqueue
spec:
  namespaceSelector: {}
  resourceGroups:
    - coveredResources: ["nvidia.com/gpu"]
      flavors:
        - name: "h100-flavor"
          resources:
            - name: "nvidia.com/gpu"
              nominalQuota: 0
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: LocalQueue
metadata:
  name: v100-localqueue
  namespace: ja-ope-test
spec:
  clusterQueue: v100-clusterqueue
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: LocalQueue
metadata:
  name: a100-localqueue
  namespace: ja-ope-test
spec:
  clusterQueue: a100-clusterqueue 
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: LocalQueue
metadata:
  name: h100-localqueue
  namespace: ja-ope-test
spec:
  clusterQueue: h100-clusterqueue 
